# NUMPY  


In [1]:
#numerical python(numpy.org)
#arrays


In [2]:
import numpy as np

In [5]:
a=np.array(45)
print(a,type(a))          #scalar and n dimensional array

45 <class 'numpy.ndarray'>


In [7]:
print(a.ndim)    #number of dimensions

0


In [8]:
a=np.array([1,2,3,4])
print(a,type(a),a.ndim)

[1 2 3 4] <class 'numpy.ndarray'> 1


In [9]:
a=np.array([2,3,4,5])
print(a,type(a),a.ndim)

[2 3 4 5] <class 'numpy.ndarray'> 1


In [48]:
a=np.array([[1,221,321,44],[3,4210,555,66]])
print(a,type(a),a.ndim)                        #2 dimensional array

[[   1  221  321   44]
 [   3 4210  555   66]] <class 'numpy.ndarray'> 2


In [43]:
a=np.array([[[9,8,77,1],[3121,421,52]]])
print(a,type(a),a.ndim)                       #3 dimensional array

[[list([9, 8, 77, 1]) list([3121, 421, 52])]] <class 'numpy.ndarray'> 2


In [16]:
arr=np.array([1,2,3,4],ndmin=5)
print(a,type(a),a.ndim)

[[[[[1 2 3 4]]]]] <class 'numpy.ndarray'> 5


In [22]:
print(a)

[[1 2 3 4]
 [3 4 5 6]]


In [23]:
print(a.size,a.shape)

8 (2, 4)


In [25]:
print(a.dtype)

int32


In [29]:
 print(a[0],a[1])

[1 2 3 4] [3 4 5 6]


In [34]:
b=np.array([1,2,3,4,5,6])           #performing mathematical ops with same length
c=np.array([2,2,2,2,2,2])

In [39]:
print(b+c)                          #only when len(b)==len(C)
print(b-c)
print(b*c)
print(b/c)
print(b%c)
print(b//c)
print(b*2)                           #broadcasting of numpy array

[3 4 5 6 7 8]
[-1  0  1  2  3  4]
[ 2  4  6  8 10 12]
[0.5 1.  1.5 2.  2.5 3. ]
[1 0 1 0 1 0]
[0 1 1 2 2 3]
[ 2  4  6  8 10 12]


In [41]:
b[0]=2                               #updatingg
print(b)

[2 2 3 4 5 6]


In [49]:
print(np.sort(b))                       #sorting in ascendong order
print(np.sort(a))                       

[2 2 3 4 5 6]
[[   1   44  221  321]
 [   3   66  555 4210]]


In [50]:
print(np.sort(b)[::-1])                 #sorting in descending ordee

[6 5 4 3 2 2]


In [51]:
cmp=np.array(1+2j)
print(type(cmp))

<class 'numpy.ndarray'>
